config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',      to:'static_pages#help'
  get '/about',     to:'static_pages#about'
  get '/signup',    to:'users#new'
  get '/login',     to:'sessions#new'
  post '/login',    to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:index, :show, :create, :destroy]
  resources :relationships, only:[:create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only:[:edit, :update]
  before_action :valid_user, only:[:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "パスワードをリセットしました"
      redirect_to root_url
    else
      flash.now[:danger] = "Emailが間違っています"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset"
      redirect_to @user
    else
      render 'edit' 
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email:params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'パスワードの再設定') %>
<h1 class="formTitle">パスワードの再設定</h1>
<div class="formIcon">
  <%= image_tag "blue-bird.jpg", class:"formIcon__img" %>
</div>
<div class="form">
  <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= hidden_field_tag :email, @user.email %>
    <div class="form__element">
      <%= f.label :password, class: "form__label" %>
      <%= f.password_field :password, class:"form__input", placeholder:"password" %>
    </div>
    <div class="form__element">
      <%= f.label :password_confirmation, "Passwordの確認", class: "form__label" %>
      <%= f.password_field :password_confirmation, class:"form__input", placeholder:"Passwordの確認" %>
    </div>
    <%= f.submit "Update Password", class: "form__btn" %>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "パスワード忘れた")%>
<h1 class="formTitle">パスワードを忘れた</h1>
<div class="formIcon formIcon--login">
  <%= image_tag "blue-bird.jpg", class:"formIcon__img" %>
</div>
<div class="form">
  <%= form_for(:password_reset, url:password_resets_path) do |f| %>
  <div class="form__element">
    <%= f.label :email, class: "form__label" %>
    <%= f.email_field :email, class:"form__input", placeholder:"email" %>
  </div>
  <%= f.submit "送信", class: "form__btn" %>
  <% end %>
</div>