config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',      to:'static_pages#help'
  get '/about',     to:'static_pages#about'
  get '/signup',    to:'users#new'
  get '/login',     to:'sessions#new'
  post '/login',    to:'sessions#create'
  delete '/logout', to:'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only:[:edit]
  resources :password_resets, only:[:new, :create, :edit, :update]
  resources :microposts, only:[:index, :show, :create, :destroy]
  resources :relationships, only:[:create, :destroy]
  resources :likes, only:[:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <p>作成日：2020/4  by Masashi</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <div class="header__elements">
      <div class="header__logo">
        <%= link_to "sample app", root_path, class: "header__logo" %>
      </div>
      <div id="toggle" class="header__menu">
        <a href="#", class="header__menuLink">Menu</a>
      </div>
      <nav class="header__nav">
        <ul id="menu" class="header__ul">
          <% if logged_in? %>
            <li class="header__navList"><%= link_to "Home", user_path(current_user), class:"header__navLink" %></li>
            <li class="header__navList"><%= link_to "ユーザー一覧", users_path, class:"header__navLink" %></li>
            <li class="header__navList"><%= link_to "投稿一覧", microposts_path, class:"header__navLink" %></li>
            <li class="header__navList"><%= link_to "編集", edit_user_path(current_user), class:"header__navLink" %></li>
            <li class="header__navList"><%= link_to "Log out", logout_path, method: :delete, class:"header__navLink" %></li>
          <% else %>
            <li class="header__navList"><%= link_to "Log in", login_path, class:"header__navLink" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="contents">
      <% flash.each do |message_type, message| %>
        <div class="alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>